import type { Metadata } from "next";
import { Content, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page"
import Accueil from "./accueil/page";
import Footer from "@/components/Footer/footer";
import FAQ from '@/components/FAQ/FAQ';
import HeroSection from "@/components/HeroSection/HeroSection";
import Tarif from "@/components/Tarifs/Tarif";
import Card from "@/components/Cards/Card";
import Bloc from "@/components/block/bloc";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My-drive",
  description: "Generated by create next app",
  icons: {
    icon: ['/favicon.ico'],
    apple: ['/apple-touch-icon.png'],
    shortcut: ['/apple-touch-icon.png']
  }
  
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar/>
        <HeroSection/>    
        <Bloc/>   
        <Card/>
        {children}
        <Tarif/>
        <FAQ/>
        <Footer/>
        
      </body>
    </html>
  );
}
